### ISSUE TITLE
Ignore `export default`

### ISSUE THREAD

**Issue by mbrookes** [jquense/jarle#1]
Minimal example:

```jsx
import * as React from 'react';

export default function foo() {
  return <div>bar</div>;
}
```
```
SyntaxError: Unexpected token 'export'
```

Thanks!

**Comment by jquense** [comment]
Is this feature request? Can you talk through why you want this to work vs not including the export in the example?

**Comment by jquense** [comment]
meh this was easy enough to add, it's newest release 👍

**Comment by mbrookes** [comment]
Thanks for that. The demos in Material-UI are all fully worked examples that can be copied, or launched in CodeSandbox. I had fixed it on my end, but thought it might be worth raising here.

While I'm here, and rather than open an issue for a question – how do you suggest dealing with mixed imports, such as this in `resolveImports`? 
```js
import RadioGroup, { useRadioGroup } from '@material-ui/core/RadioGroup';
```

 (And if there's somewhere else you'd prefer these sorts of questions, let me know 🙂 )

**Comment by jquense** [comment]
Issues are fine for questions, also can ping me in the reactiflux discord if it's be easier to chat sync. Easier for me to remember issues tho.

On this question do mixed imports not work already?  The resolver would just need to return the module, the sandbox "compiles" the import statements to `require()` calls that handle both named and default imports. Maybe I missed this specific case?
