### ISSUE TITLE
Using mixed imports in resolveImports

### ISSUE THREAD

**Issue by mbrookes** [jquense/jarle#2]
How do you suggest dealing with mixed imports, such as this in `resolveImports`? 
```js
import RadioGroup, { useRadioGroup } from '@material-ui/core/RadioGroup';
```

_Originally posted by @mbrookes in https://github.com/jquense/jarle/issues/1#issuecomment-765816752_

**Comment by mbrookes** [comment]
Grrr, sorry, caught the enter key before I was done converting a comment to an issue, and it auto-populated the title.

I guess my question is how to represent those imports in the object that `resolveImports` returns?

My best guess was to treat them both as named imports, so `'@material-ui/core/RadioGroup': { RadioGroup, useRadioGroup }`, but that doesn't seem to work.

**Comment by jquense** [comment]
> I guess my question is how to represent those imports in the object that resolveImports returns?

like an ES module would: `'@material-ui/core/RadioGroup': { default: RadioGroup, useRadioGroup }` default exports are really just a named export called 'default'. 

you could map them this way, which does the same thing:
```
import * as RadioGroupImports from '@material-ui/core/RadioGroup';

... 
{
'@material-ui/core/RadioGroup': RadioGroupImports
}
```
