### ISSUE TITLE
Not currently working with Vite

### ISSUE THREAD

**Issue by Adam-Collier** [jquense/jarle#9]
Hey! I tried to get Jarle up and running with Vite, however I ran into an issue:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/20065745/132870913-51037c4c-098e-4954-9a66-80d1ad2a319d.png">

Not sure if this is something you want to fix but I wanted to make you aware of it 😃

**Comment by jquense** [comment]
I guess we'd have to tell Vite to ignore it. any idea if that's possible?

**Comment by Adam-Collier** [comment]
The warning does mention `If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.` so that comment could be added in the import call?
